### PR TITLE
Fix for login continuation (Mx8)

### PR DESCRIPTION
**Pull request by wrdsnd**
This appends a continuation parameter to the login.html page to continue to the correct page after login.

### CODE REVIEW

**Comment by Robinfr** [comment]
@wrdsnd For some reason, for this one the formatting has completely changed? How did you format it?

**Comment by wrdsnd** [comment]
@Robinfr with the built-in Idea formatter. Which formatter was used on your branch?

**Comment by Robinfr** [comment]
@wrdsnd I just used the Eclipse one.

**Comment by Robinfr** [comment]
@wrdsnd Perfect!

**Pull request merged**
